// admin/components/ui/loading.tsx
// Loading.tsx
import React from 'react';

const Loading: React.FC = () => (
  <div
    style={{
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      height: '100%'
    }}
  >
    <div className="spinner" />
    <style jsx>{`
      .spinner {
        width: 40px;
        height: 40px;
        border: 4px solid rgba(0, 0, 0, 0.1);
        border-top-color: #0070f3;
        border-radius: 50%;
        animation: spin 1s linear infinite;
      }
      @keyframes spin {
        to {
          transform: rotate(360deg);
        }
      }
    `}</style>
  </div>
);

export default Loading;

// frontend/src/components/Loading.vue
<template>
  <div class="flex justify-center items-center p-0 m-0">
    <div class="spinner"></div>
  </div>
</template>

<style scoped>
.spinner {
  width: 16px;
  height: 16px;
  border: 4px solid white;
  border-top-color: #10d0b6;
  border-radius: 50%;
  animation: spin 1s ease-in-out infinite;
}

@keyframes spin {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
</style>
